<div class="tab-homologa">
<h3>Futebolcard</h3>
	<table>
		<tr>
			<th>Nome Homologa</th>
			<th>Chamado</th>
			<th>Skin</th>
			<th>Status</th>
			<th>Ação</th>
		</tr>
<?php 
$i = 0;
$qtd = 5 ;
while ($i < $qtd) {
	?>


	<tr>
			<td>Homologa FC <?php echo $i+1; ?> </td>
			<td>321<?php echo $i; ?> </td>
			<td>futebolcard</td>
			<td>Em Homologação</td>
			<td>editar</td>
		</tr>





<?php
$i++;
}
?>
	</table>
</div>

<div class="tab-homologa">
<h3>Socio Torcedor</h3>
	<table>
		<tr>
			<th>Nome Homologa</th>
			<th>Chamado</th>
			<th>Skin</th>
			<th>Status</th>
			<th>Ação</th>
		</tr>
<?php 
$i = 0;
$qtd = 5 ;
while ($i < $qtd) {
	?>


	<tr>
			<td>Homologa ST <?php echo $i+1; ?> </td>
			<td>321<?php echo $i; ?> </td>
			<td>futebolcard</td>
			<td>Em Homologação</td>
			<td>editar</td>
		</tr>





<?php
$i++;
}
?>
	</table>
</div>

<div class="tab-homologa">
<h3>Bilheteria</h3>
	<table>
		<tr>
			<th>Nome Homologa</th>
			<th>Chamado</th>
			<th>Skin</th>
			<th>Status</th>
			<th>Ação</th>
		</tr>
<?php 
$i = 0;
$qtd = 2 ;
while ($i < $qtd) {
	?>


	<tr>
			<td>Homologa Bilheteria <?php echo $i+1; ?> </td>
			<td>321<?php echo $i; ?> </td>
			<td>futebolcard</td>
			<td>Em Homologação</td>
			<td>editar</td>
		</tr>





<?php
$i++;
}
?>
	</table>
</div>