<?php echo $this->doctype(); ?>
<html>
    <head>
        <meta charset="UTF-8">
        <title> Controle Homologa </title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
				    <!-- favicon -->
				    <link rel="apple-touch-icon" sizes="57x57" href="/icon/apple-icon-57x57.png">
				    <link rel="apple-touch-icon" sizes="60x60" href="/icon/apple-icon-60x60.png">
				    <link rel="apple-touch-icon" sizes="72x72" href="/icon/apple-icon-72x72.png">
				    <link rel="apple-touch-icon" sizes="76x76" href="/icon/apple-icon-76x76.png">
				    <link rel="apple-touch-icon" sizes="114x114" href="/icon/apple-icon-114x114.png">
				    <link rel="apple-touch-icon" sizes="120x120" href="/icon/apple-icon-120x120.png">
				    <link rel="apple-touch-icon" sizes="144x144" href="/icon/apple-icon-144x144.png">
				    <link rel="apple-touch-icon" sizes="152x152" href="/icon/apple-icon-152x152.png">
				    <link rel="apple-touch-icon" sizes="180x180" href="/icon/apple-icon-180x180.png">
				    <link rel="icon" type="image/png" sizes="192x192"  href="/icon/android-icon-192x192.png">
				    <link rel="icon" type="image/png" sizes="32x32" href="/icon/favicon-32x32.png">
				    <link rel="icon" type="image/png" sizes="96x96" href="/icon/favicon-96x96.png">
				    <link rel="icon" type="image/png" sizes="16x16" href="/icon/favicon-16x16.png">

				    <meta name="msapplication-TileImage" content="/icon/ms-icon-144x144.png">
				    <meta name="msapplication-TileColor" content="#ffffff">
				    <meta name="theme-color" content="#ffffff">

				    <link rel="manifest" href="/lib/js/manifest.json">
				    
				    <link href="/lib/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <link href="/lib/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <link href="/lib/css/estilo.css" rel="stylesheet" type="text/css" />
	
        <script src="/lib/js/jquery/jquery.min.js"></script>
        <script src="/lib/js/bootstrap/bootstrap.min.js" type="text/javascript"></script>
        <script src="/lib/js/jquery/jquery-ui.min.js" type="text/javascript"></script>
        
				    <script src="/lib/js/status.js" type="text/javascript"></script>
				    <script src="/lib/js/traducao.js" type="text/javascript"></script>
				    
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
				<div class="opcao">
				    <a href="/">index</a>
				    <a href="/statusHomologa/cadastro">cadastro</a>
				</div>
		    <?php echo $this->layout()->content; ?>
    </body>
</html>
