
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
	<head>
		<meta charset="UTF-8" />
		<!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
		<title>Login and Registration Form with HTML5 and CSS3</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
		<meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
		<meta name="author" content="Codrops" />
		<link rel="shortcut icon" href="icon/avicon.ico"> 
		<!-- <link rel="stylesheet" type="text/css" href="css/demo.css" /> -->
		<link rel="stylesheet" type="text/css" href="lib/css/login.css" />
		<!-- <link rel="stylesheet" type="text/css" href="css/animate-custom.css" /> -->
	</head>
	<body>
		<div class="container">
				   <section>                
				<div id="container_demo" >

					<a class="hiddenanchor" id="toregister"></a>
					<a class="hiddenanchor" id="tologin"></a>
					<div id="wrapper">
						<div id="login" class="animate form">
							<form  action="/login/logar" autocomplete="on"> 
								<h1>Log in</h1> 
								<p> 
									<label for="username" class="uname" data-icon="u" > Usuário </label>
									<input id="username" name="username" required="required" type="text" placeholder="Seu login"/>
								</p>
								<p> 
									<label for="password" class="youpasswd" data-icon="p"> Senha </label>
									<input id="password" name="password" required="required" type="password" placeholder="Sua senha..." /> 
								</p>
								<p class="login button"> 
									<input type="submit" value="Login" /> 
								</p>

							</form>
						</div>


					</div>
				</div>  
			</section>
		</div>
	</body>
</html>